"""Doxygen XML generation for the C++ handler."""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path
from shutil import which
from typing import Any

from mkdocstrings import CollectionError

from mkdocstrings_handlers.cpp._internal.config import CppConfig


@dataclass(slots=True)
class DoxygenResult:
    """Paths produced by a Doxygen run."""

    build_dir: Path
    doxyfile: Path
    xml_dir: Path
    index_xml: Path


class DoxygenRunner:
    """Generate and cache Doxygen XML."""

    def __init__(self, config: CppConfig, base_dir: Path) -> None:
        self.config = config
        self.base_dir = base_dir
        self.build_dir = config.resolve_build_dir(base_dir)
        self.xml_dir = self.build_dir / "xml"
        self.doxyfile = self.build_dir / "Doxyfile"
        self.index_xml = self.xml_dir / "index.xml"

    def ensure_xml(self) -> DoxygenResult:
        """Generate XML if the cache is missing or stale."""
        doxyfile_text = self._render_doxyfile()
        if self._needs_regeneration(doxyfile_text):
            self._run(doxyfile_text)
        return DoxygenResult(
            build_dir=self.build_dir,
            doxyfile=self.doxyfile,
            xml_dir=self.xml_dir,
            index_xml=self.index_xml,
        )

    def _needs_regeneration(self, doxyfile_text: str) -> bool:
        if not self.index_xml.is_file() or not self.doxyfile.is_file():
            return True
        if self.doxyfile.read_text(encoding="utf-8") != doxyfile_text:
            return True

        index_mtime = self.index_xml.stat().st_mtime
        return any(path.stat().st_mtime > index_mtime for path in self._source_files())

    def _run(self, doxyfile_text: str) -> None:
        if which(self.config.doxygen_bin) is None:
            raise CollectionError(
                f"'{self.config.doxygen_bin}' was not found on PATH; install Doxygen "
                "or configure 'doxygen_bin'",
            )

        self.build_dir.mkdir(parents=True, exist_ok=True)
        self.doxyfile.write_text(doxyfile_text, encoding="utf-8")

        try:
            process = subprocess.run(
                [self.config.doxygen_bin, str(self.doxyfile)],
                cwd=self.base_dir,
                check=False,
                text=True,
                capture_output=True,
                timeout=self.config.doxygen_timeout,
            )
        except subprocess.TimeoutExpired as error:
            raise CollectionError(
                f"Doxygen timed out after {self.config.doxygen_timeout}s; "
                f"increase 'doxygen_timeout' or check for circular includes",
            ) from error

        if process.returncode != 0:
            message = process.stderr.strip() or process.stdout.strip()
            raise CollectionError(f"Doxygen failed with exit code {process.returncode}: {message}")
        if not self.index_xml.is_file():
            raise CollectionError(f"Doxygen did not produce XML index at {self.index_xml}")

    def _source_files(self) -> list[Path]:
        files: list[Path] = []
        patterns = self.config.file_patterns
        for input_path in self.config.resolve_input_paths(self.base_dir):
            if input_path.is_file():
                files.append(input_path)
                continue
            if not input_path.is_dir():
                continue
            for pattern in patterns:
                iterator = (
                    input_path.rglob(pattern)
                    if self.config.recursive
                    else input_path.glob(pattern)
                )
                files.extend(path for path in iterator if path.is_file())
        return files

    def _render_doxyfile(self) -> str:
        values: dict[str, Any] = {
            "PROJECT_NAME": self.config.project_name,
            "OUTPUT_DIRECTORY": self.build_dir,
            "GENERATE_XML": "YES",
            "XML_OUTPUT": "xml",
            "GENERATE_HTML": "NO",
            "GENERATE_LATEX": "NO",
            "XML_PROGRAMLISTING": "NO",
            "RECURSIVE": "YES" if self.config.recursive else "NO",
            "INPUT": self.config.resolve_input_paths(self.base_dir),
            "FILE_PATTERNS": self.config.file_patterns,
            "BUILTIN_STL_SUPPORT": "YES",
            "EXTRACT_ALL": "NO",
            "EXTRACT_PRIVATE": "NO",
            "EXTRACT_STATIC": "YES",
            "HIDE_UNDOC_MEMBERS": "NO",
            "QUIET": "YES",
            "WARN_IF_UNDOCUMENTED": "NO",
            "WARN_IF_DOC_ERROR": "YES",
            "WARN_NO_PARAMDOC": "NO",
        }
        for key, value in self.config.extra_doxygen.items():
            values[str(key).upper()] = value

        lines = ["# Generated by mkdocstrings-cpp. Do not edit by hand."]
        for key in sorted(values):
            lines.append(f"{key:<24}= {self._format_value(values[key])}")
        lines.append("")
        return "\n".join(lines)

    def _format_value(self, value: Any) -> str:
        if isinstance(value, bool):
            return "YES" if value else "NO"
        if isinstance(value, Path):
            return self._quote(value)
        if isinstance(value, (list, tuple)):
            return " ".join(self._format_value(item) for item in value)
        return self._quote(str(value))

    @staticmethod
    def _quote(value: Path | str) -> str:
        text = str(value)
        if not text:
            return '""'
        if any(char.isspace() for char in text) or any(char in text for char in ['"', "'"]):
            escaped = text.replace("\\", "\\\\").replace('"', '\\"')
            return f'"{escaped}"'
        return text
